### ISSUE TITLE
Use XHR to update data instead of reloading the whole page

### ISSUE THREAD

**Issue by giovanniberti** [nmaggioni/HubGraph#6]
While delivering an overall better user experience, this should also completely fix #4 without resolving to workarounds like #5.

**Comment by giovanniberti** [comment]
Should I rename XHR -> Websockets? 😉

**Comment by nmaggioni** [comment]
Nah, I don't really know if I want to go throught the hassle of managing actual WebSockets.
They are precise and efficient but a mess to implement in non-JS languages AFAIK ATM. On the other hand continuous XHRs are effective but not efficient, yet they are quite simple to implement.

I'll have to think this through as soon as I'm done with the first iteration of [gerph](https://github.com/nmaggioni/gerph).
